title: <p align="center"> Mathangi M </p>
logo: <p align="center">/assets/img/picture.PNG </p>
description:   <p align="center">
  <a href="https://www.linkedin.com/in/mathangi-rm/">LinkedIn</a> |
  <a href="https://github.com/Mathangimr">GitHub</a>
  <br>   
  I'm working as a data engineer having an experience of around 3 years,
  primarily working Python, Snowflake and ETL technologies.
  <br>
  </p>
theme: jekyll-theme-minimal
